[package]
name = "tari_deploy"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
minotari_app_grpc = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }
tari_core = { git = "https://github.com/tari-project/tari.git", branch = "feature-dan2" }
tari_wallet_daemon_client = { git = "https://github.com/tari-project/tari-dan.git", branch = "development" }
tari_dan_engine = { git = "https://github.com/tari-project/tari-dan.git", branch = "development" }

tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
serde = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

hickory-proto = "=0.25.0-alpha.2"
tonic = { version = "0.12.3", features = ["tls"] }
reqwest = { version = "0.12.9", features = ["default", "multipart", "stream", "json"] }
